apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bfech8mky-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bfech8mky-python 
  name: bfech8mky-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bfech8mky-python 
